host:
username:
password:
since:
    year:
    month:
    day:
target:
    amazon:
        mailbox:
        save_directory:
    bookwalker:
        mailbox:
        save_directory:
    melonbooks:
        mailbox:
        save_directory:
    yodobashi:
        mailbox:
        save_directory:
