host:
username:
password:
since:
    year:
    month:
    day:
target:
    amazon:
        mailbox:
        workspace:
    bookwalker:
        mailbox:
        workspace:
    melonbooks:
        mailbox:
        workspace:
    yodobashi:
        mailbox:
        workspace:
